# Generated by Django 6.0 on 2025-12-27 15:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('franchises', '0001_initial'),
        ('regions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfitabilityAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('premises_area', models.PositiveIntegerField(default=50, validators=[django.core.validators.MinValueValidator(30)], verbose_name='Площадь помещения (м²)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('startup_costs', models.DecimalField(decimal_places=2, editable=False, max_digits=15, verbose_name='Стартовые затраты (руб.)')),
                ('monthly_expenses', models.DecimalField(decimal_places=2, editable=False, max_digits=15, verbose_name='Ежемесячные расходы (руб.)')),
                ('forecasted_revenue', models.DecimalField(decimal_places=2, editable=False, max_digits=15, verbose_name='Прогноз выручки (руб.)')),
                ('payback_period', models.FloatField(editable=False, help_text='Время для возврата инвестиций', verbose_name='Срок окупаемости (мес)')),
                ('is_profitable', models.BooleanField(default=False, editable=False, help_text='Соответствует ли проект минимальному порогу', verbose_name='Рентабельность > 15%')),
                ('franchise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='franchises.franchise', verbose_name='Франшиза')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regions.region', verbose_name='Регион')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Анализ рентабельности',
                'verbose_name_plural': 'Аналитика рентабельности',
                'ordering': ['-created_at'],
            },
        ),
    ]
