# Generated by Django 6.0 on 2025-12-27 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profitabilityanalysis',
            name='forecasted_revenue',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=15, verbose_name='Прогноз выручки (руб.)'),
        ),
        migrations.AlterField(
            model_name='profitabilityanalysis',
            name='monthly_expenses',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=15, verbose_name='Ежемесячные расходы (руб.)'),
        ),
        migrations.AlterField(
            model_name='profitabilityanalysis',
            name='payback_period',
            field=models.FloatField(default=0.0, editable=False, help_text='Время для возврата инвестиций', verbose_name='Срок окупаемости (мес)'),
        ),
        migrations.AlterField(
            model_name='profitabilityanalysis',
            name='startup_costs',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=15, verbose_name='Стартовые затраты (руб.)'),
        ),
    ]
