# Generated by Django 6.0 on 2025-12-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название региона')),
                ('population', models.PositiveIntegerField(verbose_name='Население')),
                ('avg_income', models.DecimalField(decimal_places=2, help_text='Среднедушевой доход в месяц', max_digits=10, verbose_name='Средний доход (руб.)')),
                ('rent_cost_per_sqm', models.DecimalField(decimal_places=2, help_text='Средняя стоимость коммерческой аренды', max_digits=8, verbose_name='Стоимость аренды за м² (руб.)')),
                ('foot_traffic_index', models.FloatField(default=1.0, help_text='От 0.5 (низкий) до 2.0 (высокий)', verbose_name='Индекс пешеходного трафика')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
                'ordering': ['name'],
            },
        ),
    ]
