# Generated by Django 6.0 on 2026-01-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='avg_salary_coeff',
            field=models.FloatField(default=1.0, help_text='Москва=1.0, Регионы=0.6-0.9', verbose_name='Коэффициент зарплат'),
        ),
        migrations.AddField(
            model_name='region',
            name='food_cost_percent',
            field=models.FloatField(default=35.0, help_text='Варьируется от 30% до 45%', verbose_name='Доля продуктов в выручке (%)'),
        ),
        migrations.AddField(
            model_name='region',
            name='marketing_percent',
            field=models.FloatField(default=7.0, help_text='В малых городах может быть 5%, в мегаполисах - до 10%', verbose_name='Доля маркетинга в выручке (%)'),
        ),
        migrations.AddField(
            model_name='region',
            name='utility_percent',
            field=models.FloatField(default=15.0, help_text='От арендной платы', verbose_name='Доля коммунальных платежей (%)'),
        ),
    ]
