# Generated by Django 6.0 on 2025-12-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Franchise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название франшизы')),
                ('type', models.CharField(choices=[('cafe', 'Кофейня'), ('burger', 'Бургерная'), ('pizza', 'Пиццерия'), ('sushi-bar', 'Суши-бар')], max_length=20, verbose_name='Тип заведения')),
                ('initial_fee', models.DecimalField(decimal_places=2, help_text='Оплата за право использования франшизы', max_digits=12, verbose_name='Вступительный взнос (руб.)')),
                ('royalty_percent', models.FloatField(default=5.0, help_text='Процент от выручки ежемесячно', verbose_name='Роялти (%)')),
                ('min_area', models.PositiveIntegerField(default=40, verbose_name='Минимальная площадь (м²)')),
                ('avg_roi_months', models.PositiveIntegerField(help_text='По данным франчайзера', verbose_name='Средний срок окупаемости (мес)')),
            ],
            options={
                'verbose_name': 'Франшиза',
                'verbose_name_plural': 'Франшизы',
                'ordering': ['name'],
            },
        ),
    ]
